Domain:                       google.sk
Registrant:                   mmr-170347
Admin Contact:                mmr-170347
Tech Contact:                 mmr-170347
Registrar:                    MARK-0292
Created:                      2003-07-24
Updated:                      2021-06-22
Valid Until:                  2022-07-24
Nameserver:                   ns1.google.com
Nameserver:                   ns2.google.com
Nameserver:                   ns3.google.com
Nameserver:                   ns4.google.com
EPP Status:                   clientTransferProhibited, clientUpdateProhibited, clientDeleteProhibited

Registrar:                    MARK-0292
Name:                         MarkMonitor International Limited
Organization:                 MarkMonitor International Limited
Organization ID:              4847541
Phone:                        +1.2083895740
Email:                        registry.admin@markmonitor.com
Street:                       8th Floor, 70 St Mary Axe
City:                         London
Postal Code:                  EC3A 8BE
Country Code:                 UK
Created:                      2018-06-27
Updated:                      2022-04-04

Contact:                      mmr-170347
Name:                         Domain Administrator
Organization:                 Google Ireland Holdings Unlimited Company
Organization ID:              369511
Phone:                        +353.14361000
Email:                        dns-admin@google.com
Street:                       70 Sir John Rogerson's Quay
City:                         Dublin
Postal Code:                  2
Country Code:                 IE
Registrar:                    MARK-0292
Created:                      2019-06-07
Updated:                      2019-06-07